server {
    listen 80 default_server;
    root /usr/share/nginx/html;

    location /rootcrl/ {
        types { application/pkix-crl crl; }
        default_type application/pkix-crl;
        autoindex off;
    }

    location / {
        return 404;
    }
}
